"""Update Empresa and Usuario models

Revision ID: 27ecfbe820da
Revises: 78572ea40208
Create Date: 2024-10-08 17:54:16.687100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27ecfbe820da'
down_revision = '78572ea40208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome_usuario', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome_usuario')
    )
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_aifud', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('cnpj', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('cpf', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('razao_social',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('nome_fantasia',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_index('documento')
        batch_op.drop_index('email')
        batch_op.drop_index('nome_usuario')
        batch_op.create_unique_constraint(None, ['cnpj'])
        batch_op.create_unique_constraint(None, ['cpf'])
        batch_op.create_unique_constraint(None, ['codigo_aifud'])
        batch_op.drop_column('documento')
        batch_op.drop_column('nome_usuario')
        batch_op.drop_column('senha_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hash', mysql.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('nome_usuario', mysql.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('documento', mysql.VARCHAR(length=14), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('nome_usuario', ['nome_usuario'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.create_index('documento', ['documento'], unique=True)
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('razao_social',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('cpf')
        batch_op.drop_column('cnpj')
        batch_op.drop_column('codigo_aifud')

    op.drop_table('usuario')
    # ### end Alembic commands ###
