"""Initial migration

Revision ID: 78572ea40208
Revises: 
Create Date: 2024-10-08 17:18:54.315557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78572ea40208'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segmento', sa.String(length=100), nullable=False),
    sa.Column('tipo_documento', sa.String(length=4), nullable=False),
    sa.Column('documento', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nome_usuario', sa.String(length=80), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresa')
    # ### end Alembic commands ###
